---
#name: Install vector

- name: Make a directory for vector
  ansible.builtin.command: mkdir -p vector

- name: Get vector distr
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/0.23.3/vector-0.23.3-x86_64-unknown-linux-musl.tar.gz"
    dest: "./vector/vector-0.23.3-x86_64-unknown-linux-musl.tar.gz"

- name: Extract vector distr
  ansible.builtin.unarchive:
    remote_src: yes
    src: "/home/ubuntu/vector/vector-0.23.3-x86_64-unknown-linux-musl.tar.gz"
    dest: "/home/ubuntu/vector"
    extra_opts: [--strip-components=2]

- name: Move Vector into Path environment variable
  ansible.builtin.shell: cd /home/ubuntu/ && echo "export PATH=\"$(pwd)/vector/bin:\$PATH\"" >> /home/ubuntu/.profile
  args:
    executable: /bin/bash

- name: Enable user profile with additions to PATH
  ansible.builtin.shell: source /home/ubuntu/.profile
  args:
    executable: /bin/bash

- name: Create user vector
  ansible.builtin.user:
     name: vector
     shell: /bin/bash
     append: yes

- name: Create dir for vector config
  become: true
  ansible.builtin.file:
    path: /etc/vector
    owner: vector
    state: directory
    mode: 0755

- name: Create dir for vector data
  become: true
  ansible.builtin.file:
    path: /var/lib/vector
    owner: vector
    state: directory
    mode: 0755

- block:
    - name: status check
      become: true
      ansible.builtin.shell: systemctl status vector
      args:
        executable: /bin/bash
  rescue:
    - name: Copy exec and config files
      ansible.builtin.shell: cp /home/ubuntu/vector/bin/vector /usr/bin && cp /home/ubuntu/vector/etc/systemd/vector.default /etc/default && cp /home/ubuntu/vector/config/vector.toml /etc/vector
      args:
        executable: /bin/bash

- name: Start Vector
  become: true
  ansible.builtin.shell: cp -av /home/ubuntu/vector/etc/systemd/vector.service /etc/systemd/system && systemctl start vector
  args:
    executable: /bin/bash
